image: node:6.5.0
cache:
  paths:
  # - node_modules/
image: node:6.5.0
cache:
  paths:
  # - node_modules/

before_script:
  - npm config set spin false
  - npm install -g bower
  - npm install -g ember-cli
  - npm install -g phantomjs-prebuilt
  - npm install
  - bower install --allow-root

production:
  type: deploy
  script:
  - sh ./build-app.sh
  - sh ./deploy-app.sh
  - git push -f https://thiagobernardes:waldemir@gitlab.com:LAB262/55lab-webinstitutional-deploy.git HEAD:master
  only:
  - master

staging:
  type: deploy
  script:
  - sh ./build-app.sh
  - sh ./deploy-app.sh
  - git push -f https://thiagobernardes:waldemir@gitlab.com:LAB262/55lab-webinstitutional-deploy.git HEAD:test

  only:
  - test

dev:
  type: deploy
  script:
  - sh ./build-app.sh
  - sh ./deploy-app.sh
  - git push -f https://thiagobernardes:waldemir@gitlab.com:LAB262/55lab-webinstitutional-deploy.git HEAD:dev

  only:
  - dev
